project:
  type: website
  render: # Add HERE new chapters and new notebooks
    - index.qmd
    - chapters/chapter1.qmd
    - notebooks/notebook1.qmd

website:
  page-navigation: true
  title: "From text to code (WP10) - MLOps tutorial (Cluster 4)"
  site-url: "https://AIML4OS.github.io/WP10_Cluster4_MLOps_tutorial/"
  repo-url: "https://github.com/AIML4OS/WP10_Cluster4_MLOps_tutorial"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents: # Add HERE new chapters (but not the notebooks)
      - href: index.qmd
        text: Introduction
      - href: chapters/chapter1.qmd
        text: Data
      - href: chapters/chapter2.qmd
        text: Model
      - href: chapters/chapter3.qmd
        text: Serving
      - href: chapters/chapter4.qmd
        text: Monitoring

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
  ipynb:
    output: true


filters:
  - export-metadata.lua

