[project]
name = "aiml4os-wp10-mlops"
version = "0.1.0"
description = "A tutorial for building a MLOps pipeline for automatic coding"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
